### ISSUE TITLE
跨域问题求助

### ISSUE THREAD

**Issue by sukai-cheng** [Antabot/White-Jotter#136]
完全按照你博客上的配置的，跨域问题，就是走不了！

**Comment by sunweihxh** [comment]
![image](https://user-images.githubusercontent.com/20678453/117245234-1318e900-ae6d-11eb-9e6c-b937f60b9a2e.png)
遇到同样的问题，如图。

**Comment by sukai-cheng** [comment]
后端没有配置跨域
